name: inhar
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests
  - ipykernel
  - bs4
  - pandas
  - pytorch
  - torchvision
  - pathlib
  - joblib
  - tqdm
  - pydub
  - ffmpeg

